name: EGS
channels:
  - creditx
  - omgarcia
  - biobuilds
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - binutils_impl_linux-64=2.33.1=he1b5a44_7
  - binutils_linux-64=2.33.1=h9595d00_16
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - bokeh=1.4.0=py38_0
  - boost=1.69.0=0
  - boost-libs=1.69.0=h31b5956_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py38_0
  - click=7.0=py_0
  - cloudpickle=1.2.2=py_1
  - cmake=3.14.0=h52cb24c_0
  - cudatoolkit=10.2.89=hfd86e86_0
  - cudatoolkit-dev=10.1.243=h516909a_3
  - cytoolz=0.10.1=py38h516909a_0
  - dask=2.10.1=py_0
  - dask-core=2.10.1=py_0
  - dask-jobqueue=0.7.0=py_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.10.0=py_0
  - entrypoints=0.3=py38_1000
  - expat=2.2.6=he6710b0_0
  - freetype=2.10.0=he983fc9_1
  - fsspec=0.6.2=py_0
  - gcc-6=6.1.0=2
  - gcc-7=7.1.0=0
  - gcc_impl_linux-64=7.3.0=hd420e75_5
  - gcc_linux-64=7.3.0=h553295d_16
  - gfortran_impl_linux-64=7.3.0=hdf63c60_5
  - gfortran_linux-64=7.3.0=h553295d_16
  - gmp=6.1.0=1
  - gxx_impl_linux-64=7.3.0=hdf63c60_5
  - gxx_linux-64=7.3.0=h553295d_16
  - heapdict=1.0.1=py_0
  - icu=63.1=h5005445_0
  - importlib_metadata=1.5.0=py38_0
  - intel-openmp=2020.0=166
  - ipykernel=5.1.4=py38h5ca1d4c_0
  - ipython=7.12.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - isl=0.17.1=0
  - jedi=0.16.0=py38_0
  - jinja2=2.11.1=py_0
  - jpeg=9c=h14c3975_1001
  - json5=0.9.0=py_0
  - jsonschema=3.2.0=py38_0
  - jupyter_client=5.3.4=py38_1
  - jupyter_core=4.6.1=py38_0
  - jupyterlab=1.2.6=py_0
  - jupyterlab_server=1.0.6=py_0
  - krb5=1.17.1=h173b8e3_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libcurl=7.68.0=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=h4deb6c0_3
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=14_mkl
  - libpng=1.6.37=hed695b0_0
  - libsodium=1.0.17=h516909a_0
  - libssh2=1.8.2=h1ba5d50_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - locket=0.2.0=py_2
  - markupsafe=1.1.1=py38h516909a_0
  - mistune=0.8.4=py38h516909a_1000
  - mkl=2019.5=281
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.0.15=py38ha843d7b_0
  - mkl_random=1.1.0=py38h962f231_0
  - mpc=1.0.1=0
  - mpfr=3.1.2=0
  - msgpack-python=0.6.2=py38hc9558a2_0
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=he6710b0_1
  - notebook=6.0.3=py38_0
  - numpy=1.18.1=py38h4f9e942_0
  - numpy-base=1.18.1=py38hde5b4d6_1
  - olefile=0.46=py_0
  - openssl=1.1.1d=h516909a_0
  - packaging=20.1=py_0
  - pandas=1.0.1=py38hb3f55d8_0
  - pandoc=2.9.1.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.6.1=py_0
  - partd=1.1.0=py_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.0.0=py38hb39fc2d_0
  - pip=20.0.2=py38_1
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - psutil=5.6.7=py38h516909a_0
  - ptyprocess=0.6.0=py_1001
  - pybind11=2.4.3=py38hc9558a2_1
  - pygments=2.5.2=py_0
  - pyparsing=2.4.6=py_0
  - pyrsistent=0.15.7=py38h516909a_0
  - python=3.8.1=h0371630_1
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyyaml=5.3=py38h516909a_0
  - pyzmq=18.1.1=py38h1768529_0
  - readline=7.0=h7b6447c_5
  - rhash=1.3.8=h1ba5d50_0
  - scipy=1.4.1=py38h921218d_0
  - send2trash=1.5.0=py_0
  - setuptools=45.1.0=py38_0
  - six=1.14.0=py38_0
  - sortedcontainers=2.1.0=py_0
  - sqlite=3.31.1=h7b6447c_0
  - tbb=2019.9=hc9558a2_1
  - tbb-devel=2019.9=hc9558a2_1
  - tblib=1.6.0=py_0
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py38h516909a_3
  - traitlets=4.3.3=py38_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py38_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.2.2=h516909a_1
  - zeromq=4.3.2=he1b5a44_2
  - zfpy=0.5.5=py38hb3f55d8_0
  - zict=1.0.0=py_0
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - cycler==0.10.0
    - kiwisolver==1.1.0
    - matplotlib==3.1.3

